apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgAHFoJVys0njlwyclCB6aBowX4B+S3o9yFTzjNa+WGh2LY6DAiu6y1NH7jA1JAGvj2WSXSNx86XpSAfWqXqrWcGjNqswoBnYT08Q62Iy4QyTBAN/M1FAEy2Figf97i3uwFnNj8hu0Er/VQsiBUXHIzgGB/peKHF/NM6J24UQTfFAxD2bWwI9j99xWCg9q65u/IQDbEW1J3oxmpPChnKcRpRpjUNaG6l90LY2zxErslLo1mdzl0tVeMLUzTu14P7R93a4s59w/xxW+BDuCJd+IvV3NifBu5FtpbIZOKU3HkhXHrOvsbNMh7rLbLehQslqLc43n1JgE/q8J0mHnrWZXtNt2nWYy+w+lpDrks7KT1q594LAov6uTfhiWhbfkPku9+w1u/E98nYaguoOgK5HsciFCsDCGi5IVlisdCWWYMlpp2kGYfJB861nfXQ76kn8L9brAg4Rl0YoUW/bzqRqKhqzrbY3qpHB/THkny6XKaAjtI7NIb8RmWNjzftD4To+D6F5FxJljMfJ2+wUqUjziiWMu5ixW5ZKDX1okOafCtjeJs8GlAu4C0ZKk69QQUCM1E4KjfKQOuQVltg8qOcoKGlo2MGYrY3dRXwYEraba3avqgOdEBUR1eO8sc8rbvdmWzDGr9WpiNCIjR+G0Dr1jgordM46H8Luy4x1PJSVmysR6/ciJbUnGvWB5rfBQBwHkFXdAgTVSneqT4=
    user: AgCOtHcpasGRwODuiweMLkdU/azdcKS+CI0hP2x+XJHu0UPOUDy4fqG8XyGA+kDx2QmzgNumhJG3q1w/CusvdK3jug9uFaOtVKo96JEdm9IA7/BYBi/yG6cOu5ZPhgipatMr6sXOVDzTa4fTeB4hYzJhO8roAnCUbrSCk2lGEF55drhHCOCOnget+apv7DGwczYpPb56GDFb3uTcBkJl+ABu4sLN0Qafg7SN36x19zwfEzB51fZD+789X+XuhNVT4IRIqz64G5KZd/SYWLbIzw+QAw+2RTOGjqqw7ZoUIfMQ8AbAXJPykssERM3dBBWRA43nO0ZDHSFKQg74MzSP0K0u/dNDXBjMwVQZoz1f3O00UZhNBlBABHZ7rH0GWr72B52VGjUCKi01OLhEO0ZidnAiN5kkYpfWJm/J0soxukRBHU8Ad12mv0Ixqg9aYZ4hrKiy2Ewg7LXtJ3F07cy0R+311KuT1oi5YWTBcS0iysPwtxwBE6ZUz2eUjONBbWXnoRORlUbFQB0Lgabf1857aC3MmdB1EzrScDI1H9O5RUMaV17DJeDHxQcH281eQ3+dgW/MfPCkHCPIw1svC9KYr9E/Ww+pftvZC+mc3BGaBx1X1KN7FgNcLDbKnnzkjXPQhzVdLkP4BtzffvrVYi4/IvZFql97jYM8B7hhx5kWNCLFRgYHZqgEpY/zPRnD0PeHlQHV1acGrA==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
      
